# Generated by Django 4.0.6 on 2022-07-07 07:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'temperature'), (2, 'pressure'), (3, 'nfc')], default=1)),
                ('mode', models.IntegerField(choices=[(1, 'sensor'), (2, 'acutator'), (3, 'master')], default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('parent_node_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.node')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
        ),
        migrations.CreateModel(
            name='NodeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_data', models.BigIntegerField()),
                ('node_type', models.IntegerField(choices=[(1, 'temperature'), (2, 'pressure'), (3, 'nfc')], default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('timestamp', models.BigIntegerField(null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.node')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
        ),
    ]
